# Generated by Django 4.2.30 on 2026-04-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('inn', models.CharField(max_length=12)),
                ('legal_address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='PassportSeries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_fio', models.CharField(max_length=250)),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('passport_series', models.CharField(max_length=4)),
                ('passport_number', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=600)),
                ('start_date', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appex.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appex.position')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appex.role')),
            ],
        ),
    ]
