# Generated by Django 4.2.30 on 2026-04-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appex.passportseries'),
        ),
    ]
